/**
 * Valores de EJEMPLO para previsualizar y probar plantillas de correo con
 * datos realistas (no {{variables}} crudas). Cubre todas las variables del
 * sistema de correos de NOVARA.
 */
export const EMAIL_SAMPLE_VARS: Record<string, string> = {
  nombre: "María",
  apellido: "García",
  nombre_completo: "María García",
  email: "maria@example.com",
  nivel: "B2",
  idioma: "Inglés",
  preparacion: "B2 First (FCE)",
  progreso: "68",
  racha: "12",
  puntos: "2.350",
  lecciones_completadas: "34",
  fecha: "15 de marzo de 2026",
  fecha_examen: "20 de junio de 2026",
  precio_anterior: "89 €",
  precio_actual: "59 €",
  descuento: "30",
  codigo_cupon: "NOVARA30",
  fecha_fin_oferta: "31 de diciembre",
  dias: "5",
  area: "Writing (expresión escrita)",
  areas: "Writing y Listening",
  leccion: "Unit 5 — Travel & Experiences",
  puntuacion: "162 / 190",
  logro: "Racha de 10 días",
  descripcion_logro: "Has estudiado 10 días seguidos sin fallar.",
  contenido: "Nuevo bloque de vocabulario: viajes y transporte.",
  titulo: "Mejoras en la plataforma",
  descripcion: "Hemos añadido nuevos simulacros y mejorado el corrector de Writing.",
  mensaje: "Gracias por tu constancia esta semana. ¡Vas muy bien!",
  ejercicios: "48",
  tiempo: "3 h 20 min",
  vocabulario: "60 palabras",
  recomendacion: "Repasar los phrasal verbs de la Unidad 4.",
  enlace: "https://novara.academy/es/mi-aprendizaje",
  enlace_dashboard: "https://novara.academy/es/mi-aprendizaje",
  enlace_leccion: "https://novara.academy/es/cursos/b2-first/aprender",
  enlace_examen: "https://novara.academy/es/examenes",
  enlace_soporte: "https://novara.academy/es/soporte",
};
